import { useQuery } from '@tanstack/react-query';
import { SymbolView } from 'expo-symbols';
import { ActivityIndicator, FlatList, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '@/contexts/auth-context';
import { api } from '@/lib/api-client';

export default function AdminScreen() {
  const { user } = useAuth();
  const stats = useQuery({ queryKey: ['admin-stats'], queryFn: api.adminStats, enabled: user?.role === 'ADMIN' });
  const users = useQuery({ queryKey: ['admin-users'], queryFn: api.adminUsers, enabled: user?.role === 'ADMIN' });
  if (user?.role !== 'ADMIN') return <View style={styles.center}><Text>Admin access required.</Text></View>;
  if (stats.isLoading) return <ActivityIndicator style={styles.center} />;
  return <View style={styles.page}><View style={styles.headingRow}><SymbolView name={{ ios: 'shield.lefthalf.filled', android: 'admin_panel_settings', web: 'admin_panel_settings' }} size={25} tintColor="#17201c" /><Text style={styles.heading}>Moderation</Text></View><View style={styles.stats}><View style={styles.stat}><SymbolView name={{ ios: 'person.3.fill', android: 'group', web: 'group' }} size={18} tintColor="#17201c" /><Text>Users {stats.data?.totalUsers}</Text></View><View style={styles.stat}><SymbolView name={{ ios: 'doc.text.fill', android: 'article', web: 'article' }} size={18} tintColor="#17201c" /><Text>Posts {stats.data?.totalPosts}</Text></View><View style={styles.stat}><SymbolView name={{ ios: 'bubble.left.and.bubble.right.fill', android: 'comment', web: 'comment' }} size={18} tintColor="#17201c" /><Text>Comments {stats.data?.totalComments}</Text></View></View><View style={styles.sectionRow}><SymbolView name={{ ios: 'person.2.fill', android: 'group', web: 'group' }} size={16} tintColor="#52605a" /><Text style={styles.section}>Users</Text></View><FlatList data={users.data?.items ?? []} keyExtractor={(item) => item.id} renderItem={({ item }) => <View style={styles.row}><Text style={styles.username}>{item.displayName || item.username}</Text><Text>{item.postCount} posts - {item.isBanned ? 'Banned' : 'Active'}</Text></View>} /></View>;
}
const styles = StyleSheet.create({ page: { backgroundColor: '#f7f8f4', flex: 1, padding: 18 }, headingRow: { alignItems: 'center', flexDirection: 'row', gap: 9, marginBottom: 18 }, heading: { color: '#17201c', fontSize: 28, fontWeight: '800' }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, stat: { alignItems: 'center', backgroundColor: '#dcefe7', borderRadius: 8, color: '#17201c', flexDirection: 'row', gap: 7, padding: 14 }, sectionRow: { alignItems: 'center', flexDirection: 'row', gap: 7 }, section: { color: '#52605a', fontWeight: '700', marginTop: 24, paddingBottom: 8, textTransform: 'uppercase' }, row: { backgroundColor: '#fff', borderBottomColor: '#e1e8e3', borderBottomWidth: 1, padding: 14 }, username: { fontWeight: '700', marginBottom: 4 }, center: { alignItems: 'center', flex: 1, justifyContent: 'center' } });